### ISSUE TITLE
Box-sizing: border-box on everything

### ISSUE THREAD

**Issue by mhartz** [tmpworldwide/tmpworldwide.github.io#6]
_First, if you are unsure how box-sizing works check this [article](https://css-tricks.com/box-sizing/)._

Any arguments against using `box-sizing: border-box;` on everything as part of the standards?

Typically we have been using:

``` css
*,
*:before,
*:after {
  box-sizing: border-box;
}
```

However thanks to Sean, he found an article on [CSS-Tricks](https://css-tricks.com/inheriting-box-sizing-probably-slightly-better-best-practice/) which seems like a better practice:

``` css
html {
  box-sizing: border-box;
}
*, *:before, *:after {
  box-sizing: inherit;
}
```

The argument is that, "This will give you the same result, and make it easier to change the box-sizing in plugins or other components that leverage other behavior." You can just set the parent box-sizing to content-box and it would make all its children the same as well.

Thoughts? Ideas?
